### PR TITLE
INN-334 Forwarding query params

### PR DESCRIPTION
**Pull request by essoen**
This PR implements support for forwarding query params, i.e. forwarding query params that are not sensitive. This is first and foremost used in INN-JS (and other libraries) so it can get CrmData for unregistered user from, passed by SSOLWA through query params.
This might also be useful for other applications using Whydah.

### CODE REVIEW

**Comment by totto** [comment]
I would suggest that we continue with the Domain-Driven security approach to handling input-values also for query-param proxy to avoid unintentionally creating attack-vectors/security issues, or just a simple white-listing map for valid params we verify and allow in SPAProxy (using the applicationnmodel, so it is easy to administer the valid/allowed parameters per application in UAWA..

**Comment by essoen** [comment]
Thanks for the feedback! =) So,

1. Whitelisting instead of blacklisting
2. Define whitelistings in  Whydah application model

How about I do point number 1 first, then we get it into production, then in turn I do point 2 as a next step?

**Comment by totto** [comment]
Implementing 1+2 should take less time than implementing 1 without 2 as I see it, and would also ensure that we do not add potential inconsistency between SPAProxy HA nodes in deployments

**Comment by essoen** [comment]
I talked with Håkon to get an understanding of what you meant, and I agree with you. Will fix

**Comment by totto** [comment]
+1 -> Very good :)

**Pull request merged**
